#cloud-config
user: root
disable_root: False
password: {{ root_password }}
chpasswd:
  expire: False
ssh_authorized_keys:
- ssh-rsa {{ root_ssh_key }}
write_files:
- path: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
  content: |
    network: {config: disabled}
- path: /root/network.yaml
  content: |
{% for file in write_files %}
- {{ file }}
{%- endfor -%}

{{ network_config }}

{%- block write_files %}
{%- endblock %}

runcmd:
{%- if pre_runcmd -%}
{% for cmd in pre_runcmd %}
- {{ cmd }}
{%- endfor -%}
{%- endif %}
{% block runcmd %}{% endblock %}
{% for cmd in runcmd %}
- {{ cmd }}
{% endfor %}
{%- if post_runcmd -%}
{% for cmd in post_runcmd -%}
- {{ cmd }}
{% endfor %}
{%- endif -%}
