#cloud-config
user: root
disable_root: False
password: {{ passwords['root'].hash }}
chpasswd:
  expire: False
ssh_authorized_keys:
{%- for key in root_ssh_keys %}
- {{ key }}
{%- endfor %}
write_files:
- path: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
  content: |
    network: {config: disabled}
- path: /root/network.yaml
  content: |
{{ network_config }}
{%- if write_files %}
{%- for file in write_files %}
- path: {{ file.path }}
  content: |
    {%- for line in file.content.splitlines() %}
    {{ line }}
    {%- endfor -%}
  {%- if file.owner %}
  owner: {{ file.owner }}
  {%- endif %}
  {%- if file.permissions %}
  permissions: {{ file.permissions }}
  {%- endif %}
{%- endfor %}
{%- endif %}
{%- block write_files %}
{%- endblock %}

runcmd:
{%- if pre_runcmd -%}
{% for cmd in pre_runcmd %}
- {{ cmd }}
{%- endfor -%}
{%- endif %}
{%- if root_ssh_key_url %}
- curl -sS '{{ root_ssh_key_url }}' | egrep 'ssh-[^ ]+' | sed 's/.*\(ssh-[^ ]\+ [^ ]\+\).*/\1/' > /root/.ssh/authorized_keys
{%- endif %}
{% block runcmd %}{% endblock %}
{% for cmd in runcmd %}
- {{ cmd }}
{% endfor %}
{%- if post_runcmd -%}
{% for cmd in post_runcmd -%}
- {{ cmd }}
{% endfor %}
{%- endif -%}

{% block extra_user_data %}{% endblock %}
